version: "1"

services:
  
  db:
    image: dboffelli/ejerfinal-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: ejerciciofinal
      POSTGRES_USER: equipo
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    networks:
      - appnetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - appnetwork

  app:
    image: dboffelli/backpython
    restart: always
    ports:
      - 80:80
    networks:
      - appnetwork

networks:
  appnetwork:
